// flow-typed signature: fbb65248fe652cacf3cd1268f963ab0a
// flow-typed version: <<STUB>>/autoprefixer-stylus_v^0.13.0/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'autoprefixer-stylus'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'autoprefixer-stylus' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'autoprefixer-stylus/index' {
  declare module.exports: $Exports<'autoprefixer-stylus'>;
}
declare module 'autoprefixer-stylus/index.js' {
  declare module.exports: $Exports<'autoprefixer-stylus'>;
}
